/**
 * Copyright 2006 Webmedia Group Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

package org.araneaframework.jsp.tag.form;        

import java.io.Writer;

import javax.servlet.http.HttpServletResponse;
import javax.servlet.jsp.JspException;
import javax.servlet.jsp.PageContext;
import org.araneaframework.jsp.UiException;
import org.araneaframework.jsp.tag.UiBaseTag;
import org.araneaframework.jsp.util.UiUtil;


/**
 * Abstract base class for systemForm tags. System form maps into HTML form.
 * 
 * @author Oleg Mürk
 */
public abstract class UiSystemFormTag extends UiBaseTag {
  public final static String COUNTER_KEY = "org.araneaframework.jsp.ui.basic.UiSystemFormTag.FORM_COUNTER";  
  public final static String ID_KEY = "org.araneaframework.jsp.ui.basic.UiSystemFormTag.ID";

  public final static String GET_METHOD = "GET";
  public final static String POST_METHOD = "POST";

  public final static String SYSTEM_FORM_ID_KEY = "systemFormId";

  private String id = null;
  protected String derivedId = null;
  protected String method = null;
  protected String enctype = null;

  protected int doStartTag(Writer out) throws Exception {
    super.doStartTag(out);

    // Error check
    if (getContextEntry(ID_KEY) != null)
      throw new UiException("System forms cannot be nested");                    

    // Compute new id for systemForm.
    derivedId = id == null ? UiSystemFormTag.generateId(pageContext) : id;

    addContextEntry(ID_KEY, derivedId);
    addContextEntry(SYSTEM_FORM_ID_KEY, derivedId);    

    // Write form 
    UiUtil.writeOpenStartTag(out, "form");
    UiUtil.writeAttribute(out, "id", derivedId);
    UiUtil.writeAttribute(out, "name", derivedId);    
    UiUtil.writeAttribute(out, "method", method);
    UiUtil.writeAttribute(out, "enctype", enctype);
    UiUtil.writeAttribute(out, "accept-charset", getAcceptCharset());
    UiUtil.writeAttribute(out, "action", ((HttpServletResponse)pageContext.getResponse()).encodeURL(getFormAction()));
    UiUtil.writeAttribute(out, "style", "margin: 0px");
    UiUtil.writeAttribute(out, "onsubmit", "javascript:return false");
    UiUtil.writeCloseStartTag(out);

    // Script
    // Initialize the uiProperties object for this systemform
    // This object will store validators for UiLib forms contained in this systemform.      
    UiUtil.writeOpenStartTag(out, "script");
    UiUtil.writeAttribute(out, "type", "text/javascript");
    UiUtil.writeCloseStartTag(out);
    out.write("uiSystemFormContext(");
    UiUtil.writeScriptString(out, derivedId);
    out.write(");\n");
    UiUtil.writeEndTag(out, "script");

    // Continue
    return EVAL_BODY_INCLUDE;
  }

  protected int doEndTag(Writer out) throws Exception {
    UiUtil.writeEndTag(out, "form");

    // Continue
    super.doEndTag(out);
    return EVAL_PAGE;      
  }

  public static String generateId(PageContext pageContext){
    Long counter = (Long)pageContext.getAttribute(COUNTER_KEY, PageContext.REQUEST_SCOPE);
    if (counter == null)
      counter = new Long(0);
    else
      counter = new Long(counter.longValue() + 1);
    pageContext.setAttribute(COUNTER_KEY, counter, PageContext.REQUEST_SCOPE);
    return "system_form_" + counter;
  }

  /* ***********************************************************************************
   * Tag attributes
   * ***********************************************************************************/
  /**
   * @jsp.attribute
   *   type = "java.lang.String"
   *   required = "false"
   *   description = "Form name, autogenerated if omitted."
   */
  public void setId(String id) throws JspException {
    this.id = (String)evaluate("id", id, String.class);
  }

  /**
   * @jsp.attribute
   *  type = "java.lang.String" 
   *   required = "true" 
   *  description = "Submitting method: GET or POST." 
   */
  public void setMethod(String method) throws JspException {
    this.method = (String)evaluateNotNull("method", method, String.class);

    if (!this.method.equals(GET_METHOD) && 
        !this.method.equals(POST_METHOD))
      throw new UiException("Wrong form method value '" + method + "'");
  }

  /**
   * @jsp.attribute
   *   type = "java.lang.String"
   *   required = "false"
   *   description = "Form data encoding type." 
   */
  public void setEnctype(String enctype) throws JspException {
    this.enctype = (String)evaluate("enctype", enctype, String.class);
  }

  /* ***********************************************************************************
   * ABSTRACT METHODS
   * ***********************************************************************************/

  protected abstract String getAcceptCharset();
  protected abstract String getFormAction();
}
